spring:
  application:
    name: cloud-config-client-dev


server:
  port: 8920
  servlet:
    context-path: /config/client

# 自定义参数
my:
  motto:
    everything is inferior, only read is high
#     三更灯火五更鸡，正是男儿读书时

