
spring:
  profiles:
    include: management
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启服务的注册发现，通过eureka的serviceId转发到具体的微服务实例
          lower-case-service-id: true # 开启eureka中的服务名称小写，否则需要通过大写的服务名称访问
      routes:
      - id: gateway-one #自定义路由
        uri: http://www.ityouknow.com #目标服务地址
        predicates: #路由条件
        - Path=/spring-cloud
      - id: add_request_parameter_routes
        uri: lb://eureka-provider
        filters:
        - AddRequestParameter=foo, bar
        predicates:
        - Method=GET

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: debug

# info信息中的@@是读去maven中的配置，是在maven编译的时候把配置替换成对应的maven值，所以无法总config配置服务中获取
#info:
#  app:
#    name: gateway-demo-noe
#    version: @project.version@
#    encoding: @project.bulid.sourceEncoding@
#    java:
#      version: @java.version@
