spring:
  profiles:
    incolude: mq,encry


server:
  port: 8510
  servlet:
    context-path: /zuul


zuul:
  routes:
    baidu:
      path: /baidu/** # 重定向拦截url
      url: http://www.baidu.com # 重定向目标url

    api:
      path: /config/**
      serviceId: cloud-config-client-dev # 重定向到eureka服务上


